config/urls.py
""" Top level URLs for AppsCake project. """
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('src.urls')),
)

src/urls.py
""" Maps URL AppsCake UI paths to rendering functions in views.py. """
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns('src.views',
    url(r'^$', 'home', name='home'),
    (r'^about/$', 'about',),
    (r'^common/.*', 'common',),
    url(r'start/$', 'start'),
    url(r'terminate/$', 'terminate'),
    url(r'test/$', 'test'),
    url(r'getdeploymentstatus/$', 'get_deployment_status'),
    url(r'getterminationstatus/$', 'get_termination_status')
    )

src/forms.py
""" Form creation class for deployment options in AppScale. """
from django import forms
from django.core.validators import validate_email


# Infrastructures to choose from for cloud deployments. Tuples map form names
# to labels.
INFRAS = [
    ('ec2', 'Amazon EC2'),
    ('euca', 'Eucalyptus'),
    ('gce', 'Google Compute Engine')]

# Deployment options. Tuples map form names to labels.
DEPLOYS = [('cluster','Cluster'),
  ('cloud','Cloud')]

# Deployment type: simple or advanced. Tuples map form names to labels.
DEPLOY_TYPE = [
  ('simple', 'Simple'),
  ('advanced', 'Advanced')
]

# Different instance sizes for the user to pick from. Tuples map form names
# to labels.
MACHINE = [
  ('m1.small', 'm1.small'),
  ('m1.medium', 'm1.medium'),
  ('m1.large', 'm1.large'),
  ('m1.xlarge', 'm1.xlarge')]

class CommonFields(forms.Form):
  """ A form object for the user to deploy AppScale. """
  cloud = forms.ChoiceField(choices=DEPLOYS, required=True, label=False,
    widget=forms.RadioSelect(attrs={
    'value': '', 'onclick':
    'checkTransType(this.value)',
    'type': 'radio',
    'name': '',
    'data-required': 'true',
    'class': 'required',
    }))

  instance_type = forms.ChoiceField(choices=MACHINE, widget=forms.Select(attrs={
     'class': 'dk_fix'}))

  key = forms.CharField(label=("EC2/Eucalyptus Key"), required=True, 
    widget=forms.TextInput(attrs={
      'data-required': 'true',
      'class': 'required'}))

  secret = forms.CharField(label=("EC2/Eucalyptus Secret"), required=True, 
    widget=forms.TextInput(attrs={
      'data-required': 'true',
      'class': 'required'}))

  infrastructure = forms.ChoiceField(choices=INFRAS, widget=forms.Select(attrs={
    'id': 'infrastructure',
    'class': 'dk_fix'}))

  min = forms.IntegerField(max_value=100, min_value=1,
    widget=forms.TextInput(attrs={
      'data-required': 'true',
      'value': '1',
      'class': 'required'}))

  max = forms.IntegerField(max_value=100, min_value=1,
    widget=forms.TextInput(attrs={ 'data-required': 'true', 'id': 'amount',
    'type': 'text', 'class': 'clearfix', 'placeholder': '1' }))

  cloud = forms.CharField(widget=forms.HiddenInput(attrs={
    'readonly':'cloud'}))

  cluster = forms.CharField(widget=forms.HiddenInput(attrs={
    'readonly':'cluster'}))

  admin_email = forms.EmailField(validators=[validate_email], max_length=40,
    required=True, widget=forms.TextInput(attrs={
      'id':'email',
      'data-type':'email',
      'name':"email",
      'data-trigger':"change",
      'data-required':"true"}))

  admin_pass = forms.CharField(widget=forms.PasswordInput(render_value=False,
    attrs={
      'id':'admin_pass',
      'name':"admin_pass",
      'class': 'required parsley-validate',
      'data-minlength': '6',
      'data-required':"true"
    }), label="AppScale Admin Password", min_length=6, required=True, )

  root_pass = forms.CharField(widget=forms.PasswordInput(render_value=False,
    attrs={
      'id':'root_pass',
      'name':"root_pass",
      'class': 'required parsley-validate',
      'data-minlength': '6',
      'data-required': "true"
    }), label="Virtual Machine Root Password", min_length=6, required=True, )

  pass_confirm = forms.CharField(widget=forms.PasswordInput(render_value=False,
    attrs={
      'id':'pass_confirm',
      'class': 'required parsley-validate',
      'data-equalto': '#admin_pass',
      'name':'pass_confirm', 'data-minlength': '6',
      'data-required':"true"
    }), label="Confirm Password", min_length=6)

  cloud_admin_pass = forms.CharField(widget=forms.PasswordInput(
    render_value=False,
    attrs={'id':'cloud_admin_pass',
    'name':"admin_pass",
    'class': 'required parsley-validate',
    'data-minlength': '6',
    'data-required':"true"}),
    label="AppScale Admin Password", min_length=6)

  cloud_pass_confirm = forms.CharField(widget=forms.PasswordInput(
    render_value=False,
    attrs={'id':'cloud_pass_confirm',
    'data-equalto': '#cloud_admin_pass',
    'name':'pass_confirm',
    'data-minlength': '6',
    'data-required':"true"}),
    label="Confirm Password", min_length=6)

  keyname = forms.CharField(min_length=4, max_length=24, required=True,
    widget=forms.TextInput(attrs={
      'id':'keyname',
      'name':"keyname",
      'data-trigger':"change",
      'data-required':"true"
    }))

  ips_yaml = forms.CharField(label=("ips.yaml"), max_length=120,
    widget=forms.Textarea(attrs={
      'id':'ips_yaml',
      'name':"ips",
      'data-trigger':"change",
      'data-required':"true",
      'class': 'required'
    }),
    required=True)

  ec2_euca_url = forms.CharField(label='Eucalyptus URL',
    max_length=120, )

  deployment_type = forms.ChoiceField(label='Select Deployment Type',
    choices=DEPLOY_TYPE,
    widget=forms.Select(attrs={
    'id': 'select-required',
    'data-required': 'true',
    }))

  machine = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
    'data-required': 'true',
  }))

  #Form for JSON GCE credentials
  gceCredentials = forms.CharField(max_length=100, widget=forms.TextInput(
    attrs={
    'placeholder': 'Paste your GCE JSON credentials',
    'id': 'gce-credentials',
    'data-required': 'true',
  }))

  #Form for entering your project ID
  gceProjectId = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
    'data-required': 'true',
    'id': 'gce-project-id',
  }))

  #Form for naming your image
  gceImageName = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
    'data-required': 'true',
    'id': 'gce-image-name',
  }))

src/views.py
""" Views for different pages in particular for starting and stopping AppScale.
"""
import logging
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), "../"))
import helpers
import appscale_tools_thread
from forms import CommonFields
 
from django.http import HttpResponse
from django.http import HttpResponseServerError
from django.shortcuts import render
from django.utils import simplejson

# When deploying on virtual machines without IaaS support.
CLUSTER_DEPLOY = "cluster"

# When deploying on IaaS such as EC2 or Eucalyptus.
CLOUD_DEPLOY = "cloud"

# A global variable to store all threads deploying AppScale.
DEPLOYMENT_THREADS = {}

# A global variable to store all threads terminating AppScale.
TERMINATING_THREADS = {}

# Placement stategies for cloud deployments.
SIMPLE_DEPLOYMENT = "simple"
ADVANCE_DEPLOYMENT = "advanced"

# The location of template files.
TERMINATE_HTML_FILE_PATH = "base/terminate.html"
HOMEPAGE_HTML_FILE_PATH = "base/home.html"
ABOUT_HTML_FILE_PATH = "base/about.html"
APPSCALE_STARTED_HTML_FILE_PATH = "base/start.html"

def terminate(request):
  """ A request to the terminate page which goes and looks up a currently 
  running deployment and terminates that deployment.
  
  Args:
    request: A Django web request.
  Returns:
    A rendered version of terminate.html with the keyname passed into the 
    javascript.
  """
  get = request.GET.copy()
  if 'keyname' not in get:
    return HttpResponseServerError("Did not receive the keyname of the " \
      "instances to terminate.")

  keyname = get['keyname']
  if keyname not in DEPLOYMENT_THREADS:
    return HttpResponseServerError("Unknown keyname of the " \
      "instances to terminate.")

  appscale_up_thread = DEPLOYMENT_THREADS[keyname]

  terminate_thread = appscale_tools_thread.AppScaleDown(
    appscale_up_thread.deployment_type, keyname,
    ec2_access=appscale_up_thread.ec2_access, 
    ec2_secret=appscale_up_thread.ec2_secret,
    ec2_url=appscale_up_thread.ec2_url)

  TERMINATING_THREADS[keyname] = terminate_thread

  terminate_thread.start()

  return render(request, TERMINATE_HTML_FILE_PATH, {'keyname': keyname})

def home(request):
  """ Render the home page which takes in input from the user to start 
  AppScale. 

  Args:
    request: A Django web request.
  Returns:
    A rendered version of home.html with form fields.
  """
  return render(request, HOMEPAGE_HTML_FILE_PATH, {'form': CommonFields()})

def about(request):
  """ Render the about page that tells users about AppsCake. 

  Args:
    request: A Django web request.
  Returns:  
    A rendered version of about.html. 
  """
  return render(request, ABOUT_HTML_FILE_PATH)

def get_deployment_status(request):
  """ Returns a json string of the status of the tools being run.

  Args:
    request: A Django web request.
  Returns:
    A HttpResponse object with a json message of the current deployment status.
  """
  get = request.GET.copy()
  identifier = None
  if 'keyname' in get:
    identifier = get['keyname']
  else:
    message = {'status': 'error', 'error_message': 
      "Bad JSON request (missing keyname)."}
    return HttpResponse(simplejson.dumps(message))  

  logging.debug("Running keyname {0}".format(DEPLOYMENT_THREADS.keys()))

  if identifier not in DEPLOYMENT_THREADS:
    message = {'status': 'error', 'error_message': 
      "Unknown keyname given {0}.".format(identifier)}
  else:
    message = DEPLOYMENT_THREADS[identifier].get_status()

  return HttpResponse(simplejson.dumps(message))  

def get_termination_status(request):
  """ Returns a json string of the status of the tools being run.

  Returns:
    A HttpResponse object with a json message of the current termination status.
  """
  get = request.GET.copy()
  identifier = None
  if 'keyname' in get:
    identifier = get['keyname']
  else:
    message = {'status': 'error', 'error_message': 
      "Bad JSON request (missing keyname)."}
    return HttpResponse(simplejson.dumps(message))  

  if identifier not in TERMINATING_THREADS:
    message = {'status': 'error', 'error_message': 
      "Unknown keyname given {0}.".format(identifier)}
  else:
    message = TERMINATING_THREADS[identifier].get_status()

  return HttpResponse(simplejson.dumps(message))  


def start(request):
  """ This is the page a user submits a request to start AppScale. 

  Returns:
    A HttpResponse rendering the start page or HttpResponseServerError
    if there was an error.
  """
  if request.method == 'POST':
    form = CommonFields(data=request.POST)
    appscale_up_thread = None
    email = form['admin_email'].value()
    password = form['admin_pass'].value() or form['cloud_admin_pass'].value()
    keyname = helpers.generate_keyname()
   
    cloud_type = None
    if 'cluster' in request.POST:
      cloud_type = CLUSTER_DEPLOY
    elif 'cloud' in request.POST:
      cloud_type = CLOUD_DEPLOY

    if cloud_type == CLOUD_DEPLOY:
      infras = form['infrastructure'].value()
      deployment_type = form['deployment_type'].value()
      instance_type = form['instance_type'].value()
      machine = form['machine'].value()
      instance_type = form['instance_type'].value()
      access_key = form['key'].value()
      secret_key = form['secret'].value()
      ec2_url = form['ec2_euca_url'].value()
    #Blocked on GCE tools support
    #elif infras == form['infrastructure'].value('gce'):
      
      if not ec2_url:
        ec2_url = None

      if deployment_type == ADVANCE_DEPLOYMENT:
        ips_yaml = form['ips_yaml'].value()
        appscale_up_thread = appscale_tools_thread.AppScaleUp(cloud_type,
                                   keyname,
                                   email,
                                   password,
                                   placement=ADVANCE_DEPLOYMENT,
                                   machine=machine,
                                   instance_type=instance_type,
                                   infrastructure=infras,
                                   ips_yaml=ips_yaml,
                                   ec2_access=access_key,
                                   ec2_secret=secret_key,
                                   ec2_url=ec2_url)
      elif deployment_type == SIMPLE_DEPLOYMENT:
        min_nodes = max_nodes = form['max'].value()
        appscale_up_thread = appscale_tools_thread.AppScaleUp(cloud_type,
                                   keyname,
                                   email,
                                   password,
                                   placement=SIMPLE_DEPLOYMENT,
                                   machine=machine,
                                   instance_type=instance_type,
                                   infrastructure=infras,
                                   max_nodes=max_nodes,
                                   min_nodes=min_nodes,
                                   ec2_access=access_key,
                                   ec2_secret=secret_key,
                                   ec2_url=ec2_url)
      else:
        return HttpResponseServerError("Unable to get the deployment strategy.")
    elif cloud_type == CLUSTER_DEPLOY:
      ips_yaml = form['ips_yaml'].value()
      root_password = form['root_pass'].value()
      appscale_up_thread = appscale_tools_thread.AppScaleUp(cloud_type, 
                                   keyname,  
                                   email,
                                   password,
                                   ips_yaml=ips_yaml,
                                   root_pass=root_password)
    else:
      return HttpResponseServerError(
        "Unable to figure out the type of cloud deployment.")  

    appscale_up_thread.start()

    identifier = appscale_up_thread.keyname
    DEPLOYMENT_THREADS[identifier] = appscale_up_thread

    return render(request, APPSCALE_STARTED_HTML_FILE_PATH, {'keyname': 
      identifier})
  else:
    return HttpResponseServerError("404 Page not found")

src/templates/base/home.html
{% extends "_layouts/base.html" %}
{% block content %}

<div class="container" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="span12 hero-unit">
            <h1>Welcome to AppsCake!</h1>
            <h3>AppsCake makes deploying AppScale a piece of cake!</h3>
            <p>AppsCake currently supports deployment strategies over Amazon EC2, Eucalyptus and
                virtual machines.</p>
            <p><a href="http://www.appscale.com/" class="btn btn-primary btn-large">Learn more about AppScale &raquo;</a></p>
            <hr/>
        </div>
    </div>

    <div class="row">
        <div class="span3">
            <form action="/start/" method="post" data-validate="parsley"> {% csrf_token %}
                <label>Choose deployment infrastructure:</label>
                <label class="radio"><input class="" id="rdb1 optionsRadio1" type="radio" name="toggler" value="1" onclick="changeDeployType"/>Cluster</label>
                <label class="radio"><input class="" id="rdb2" type="radio" name="toggler" value="2"  />Cloud</label>
        </div><!--close cluster/cloud span3-->
<!--Cluster Deployment Form-->
        <div class="span12">
            <div id="blk-1" class="toHide" style="display:none">
                <div class="span4" id="clusterDiv">
                    {{ form.non_field_errors }}
                    <label for="email">Admin Email:</label>
                    {{ form.admin_email }}
                    <label for="id_admin_pass">AppScale admin password:</label>
                    {{ form.admin_pass }}
                    <label for="id_pass_confirm">Confirm password:</label>
                    {{ form.pass_confirm }}
                    <label for="id_root_pass">Virtual machine root password:</label>
                    {{ form.root_pass }}
                    {{ form.cluster }}
                    <br><br>
                    <button type="submit" style="margin:0px 0 25px
                    0px; width: 300px;" class="btn btn-large
                    btn-success pull-left">Launch Now!</button>
                </div>
                <div class="span6">
                    <p>Enter the desired deployment strategy in the dialog box below,
                        if you are unfamiliar with how this works, please visit the
                        <a href="https://github.com/AppScale/appscale/wiki/Advanced-Deployment">docs</a>.
                        Below is a sample strategy: </p>
                        <pre>
master : 192.168.33.10
appengine: 192.168.33.10
database: 192.168.33.10
zookeeper: 192.168.33.10
                        </pre>
                    <label for="id_ips_yaml">Enter your ips.yaml configuration below:</label>
                    {{ form.ips_yaml }}
                    {{ field }}
                    </form>
                </div><!--Close IPS - span6 -->
            </div><!--Closes blk-1 hidden div-->
        </div><!--Closes span12-->
    </div><!--Closes row-->

<!--Cloud Deployment Form-->
    <div class="span12">
        <div id="blk-2" class="row toHide" style="display:none">
            <div class="brd span4" id="">
                <form action="/start/" method="post" id="appscake-form" data-validate="parsley"> {% csrf_token %}
                    {{ form.cloud }}<!--Hidden Input-->
                    {{ form.non_field_errors }}
                    <label>Deployment strategy:</label>
                    {{ form.deployment_type }}
                    <label for="email">Admin Email:</label>
                    {{ form.admin_email }}
                    <label for="id_admin_pass">Admin password:</label>
                    {{ form.cloud_admin_pass }}
                    <label for="id_pass_confirm">Confirm password:</label>
                    {{ form.cloud_pass_confirm }}
                    <label for="deploy_option1">Choose infrastructure:</label>
                    {{ form.infrastructure }}
                    <div id="url">
                    <label>EC2/EUCA URL (required for Eucalyptus):</label>
                    {{ form.ec2_euca_url }}</div>
                    <div id="instance_type">
                    <label for="instance_type">Instance type:</label>
                    {{ form.instance_type }}</div>
                    <div id="access_key">
                    <label for="key">EC2/Eucalyptus Access Key:</label>
                    {{ form.key }}</div>
                    <div id="secret_key">
                    <label for="secret">EC2/Eucalyptus Secret Key:</label>
                    {{ form.secret }}</div>
                    <div id="machine_type">
                    <label>AMI/EMI:</label>
                    {{ form.machine }}</div>
                    <div id="gce_creds" style="display: none">
                    <label for="gce_creds">GCE JSON Credentials:</label>
                        {{ form.gceCredentials }}
                    </div>
                    <div id="gce_project" style="display: none">
                    <label for="gce_project">GCE Project Id:</label>
                        {{ form.gceProjectId }}
                    </div>
                    <div id="gce_image" style="display: none">
                        <label for="gce_image">GCE Image Name:</label>
                        {{ form.gceImageName }}
                    </div>
                    <br><br>
                    <button type="submit" style="margin:0px 0 25px 0px; width:
                    300px;" class="btn btn-large btn-success pull-left">Launch
                      Now!</button>
            </div>
            <div class="span7">
                <div id="advanced" class="box" >
                  <p>Enter the desired deployment strategy in the dialog box below,
                    if you are unfamiliar with how this works, please visit the
                    <a href="https://github.com/AppScale/appscale/wiki/Advanced-Deployment">docs</a>.
                    Below is a sample strategy: </p>
                    <pre>
master : 192.168.33.10
appengine: 192.168.33.10
database: 192.168.33.10
zookeeper: 192.168.33.10
                    </pre>
                    <label for="id_ips_yaml">Enter your ips.yaml configuration below:</label>
                    {{ form.ips_yaml }}
                </div><!--Close advanced input -->
                <div id="simple" class="box span4">
                    <label style="float: left;" for="amount">Maximum number of nodes to deploy over:</label>
                    <p>{{ form.max }}</p>
                    <div id="slider"></div>
                </div><!--Close simple input-->
               </form>
            </div>
        </div><!--Close hidden blk-2 -->
    </div>
{% endblock %}

src/templates/base/start.html
{% extends '_layouts/base.html' %}

{% block content %}

  <script type="text/javascript">
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      crossDomain: false, // obviates need for sameOrigin test
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type)) {
          xhr.setRequestHeader("X-CSRFToken", '{% csrf_token %}');
        }
      }
    });

  </script>

  <script type="text/javascript">

    window.onload=function(){
      $("#init").html('Initializing');
      $("#progress").css('width','0%');
      $("#progress").html('0%');
    };

    $(document).ready(function(){
      var dots = ".";
      var progresspump = setInterval(function(){
        $.getJSON("/getdeploymentstatus/",
                {"keyname": "{{ keyname }}"}, function(data){
          if(dots == "." || dots == ".."){
            dots = dots + ".";
          } else{
            dots = "." ;
          }

          if(data.status == "complete") {
            clearInterval(progresspump);
            $("#progress").css('width',"100%");
            $("#progress").html("100%");
            $("#progressouter").removeClass("active");
            $("#init").html("<a href='" + data.link + "' target='_blank'>Click here to go to your AppScale deployment</a>");
            $("#terminate").html("<a href='/terminate/?keyname={{ keyname }}' class='btn btn-danger btn-large'>Terminate AppScale</a>");
          }
          else if(data.status == 'error'){
            clearInterval(progresspump);
            $("#progress").css('width',"0%");
            $("#progress").html("ERROR");
            $("#progressouter").removeClass("active");
            $('#init').html('ERROR')
            $('#error_msg').html(data.error_message)
            $("#terminate").html("<a href='/terminate/?keyname={{ keyname }}' class='btn btn-danger btn-large'>Terminate AppScale</a>");
          }
          else if(data.status == 'running'){
            $("#progress").css('width',data.percent +'%');
            $("#progress").html(data.percent +'%');
            $('#init').html("Deploying" + dots);
          }
        })
        /*poll every 1 second*/
      }, 1000);

    });

  </script>

    <div class="container">
        <div class="row">
            <div style="text-align: center;" class="span10 hero-unit">
                <h1>AppScale Up!</h1>
                <hr>
                <h4> Your cloud is being brought up, please be patient.</h4>

                <div style="width:400px; margin-left: auto;
                margin-right: auto">
                  <div style="height: 40px" class="progress progress-success
                  progress-striped
                  active"
                       id="progressouter">
                    <div class="bar" id="progress"></div>
                  </div>
                </div>
                    <hr>
              <div style="text-align: center;">
                  <h3>AppScale Tools Status:</h3>
                  <h1 id="init"></h1>
                  <span id="error_msg"></span>
                  </br></br></br>
                  <span id="terminate"></span>
                </div>

              </div>

            </div>
        </div>
    </div>

{% endblock %}

src/templates/base/terminate.html
{% extends '_layouts/base.html' %}

{% block content %}

  <script type="text/javascript">
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      crossDomain: false, // obviates need for sameOrigin test
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type)) {
          xhr.setRequestHeader("X-CSRFToken", '{% csrf_token %}');
        }
      }
    });

  </script>

  <script type="text/javascript">

    window.onload=function(){
      $("#init").html('Terminating');
      $("#progress").css('width','0%');
      $("#progress").html('0%');
    };

    $(document).ready(function(){
      var dots = ".";
      var progresspump = setInterval(function(){
        $.getJSON("/getterminationstatus/",
                {"keyname": "{{ keyname }}"}, function(data){
          if(dots == "." || dots == ".."){
            dots = dots + ".";
          } else{
            dots = "." ;
          }

          if(data.status == "terminated") {
            clearInterval(progresspump);
            $("#progress").css('width',"100%");
            $("#progress").html("100%");
            $("#progressouter").removeClass("active");
            $("#init").html("Successfully terminated.");
            $("#terminator").css('display', "block");
          }
          else if(data.status == 'error'){
            clearInterval(progresspump);
            $("#progress").css('width',"0%");
            $("#progress").html("ERROR");
            $("#progressouter").removeClass("active");
            $('#init').html('ERROR')
            $('#error_msg').html(data.error_message)
          }
          else if(data.status == 'terminating'){
            $("#progress").css('width',data.percent +'%');
            $("#progress").html(data.percent +'%');
            $('#init').html("Terminating" + dots);
          }
        })
        .error(function() {
          clearInterval(progresspump);
          $("#progress").css('width',"100%");
          $("#progress").html("100%");
          $("#progressouter").removeClass("active");
          $("#init").html("Successfully terminated.");
          $("#terminator").css('display', "block");
        })
       /*poll every 1 second*/
      }, 1000);

    });


  </script>



    <div class="container">
        <div class="row">
            <div style="text-align: center;" class="span10 hero-unit">
                <h1>AppScale Down</h1>
                <hr>
                <h4> Your cloud is being terminated.</h4>

                <div style="width:400px; margin:25px 0 0px 280px;">
                  <div style="height: 40px" class="progress progress-danger progress-striped active"
                       id="progressouter">
                    <div class="bar" id="progress"></div>
                  </div>
                </div>
                    <hr>
              <div style="text-align: center;">
                  <h3>AppScale Tools Status:</h3>
                  <h1 id="init"></h1>
                  <span id="error_msg"></span>
                  <span id="terminator" style="display: none;">
                    <img src="{{ STATIC_URL }}/img/terminator-main.jpeg" />
                  </span>
                </div>

              </div>

            </div>
        </div>
    </div>

{% endblock %}